Wip add todo popup almost done
WebDesign3-DHBW/GrouBee pull request #22
Opened 2021-05-10 09:32 UTC by NataschaForster

2021-05-10 14:48 UTC, OleMantei commented on src/components/List/AddCard.js
> +        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle} variant="h1">
```suggestion
        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle}>
        <Typography variant="h3" component="h2">{cardTitle} hinzufügen</Typography>
        </DialogTitle>
```

2021-05-10 14:50 UTC, OleMantei commented on src/components/List/AddCard.js
> +        </DialogTitle>
variant funktioniert bei DialogTitle nicht, oder?

2021-05-10 14:54 UTC, felixkeller98 commented on src/components/List/AddCard.js
> +        </DialogTitle>
Jo hast recht das "variant="h1"" kann raus.
DialogTitle setzt das automatisch auf h2 also das Typography brauchen wir nicht bzw. React beschwert sich wenn wir eine h2 in eine h2 nesten

2021-05-10 14:55 UTC, felixkeller98 commented on src/components/List/AddCard.js
> +        </DialogTitle>
Und ja der Titel bestimmt da die Breite ^^

2021-05-10 14:55 UTC, eisenils approved these changes
Richtig cool, dass auch gleich alle Personen der Gruppe angezeigt werden. Finde ich nice 😄

2021-05-10 14:55 UTC, eisenils commented on src/components/List/AddCard.js
> +    backgroundColor: "white",
Ne bitte nicht so, weil sonst bei Darkmode ist 😵

2021-05-10 14:55 UTC, eisenils commented on src/components/List/AddCard.js
> +        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle} variant="h1">
Komische id...
Ist vielleicht etwas groß oder? Vielleicht mal andere Variante ausprobieren :)

2021-05-10 14:55 UTC, eisenils commented on src/components/List/AddCard.js
> +              <InputLabel htmlFor="zuständiger">Zuständige*r</InputLabel>
```suggestion
              <InputLabel htmlFor="zuständiger">Zuständig</InputLabel>
```
Spart uns die Genderformulierung und ist neutraler oder? 😃

2021-05-10 14:55 UTC, eisenils commented on src/components/List/List.js
> +    return <p>Loading...</p>;
Da könnten wir ein Loading Circle machen oder? :)

2021-05-10 14:55 UTC, eisenils commented on src/components/List/AddCard.js
> +      }); // Liste abstrahieren
Hat das noch Relevanz oder kann das weg? 😅

2021-05-10 14:55 UTC, felixkeller98 commented on src/components/List/AddCard.js
> +        </DialogTitle>
```suggestion
        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle}>
          {cardTitle} hinzufügen
        </DialogTitle>
```

2021-05-10 14:58 UTC, eisenils commented on src/components/List/AddCard.js
> +        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle} variant="h1">
Also in Zeile 124 :D

2021-05-11 08:41 UTC, OleMantei commented on src/components/Cleaning/Cleaning.js
> +      ></AddCard>
```suggestion
      />
```

2021-05-11 08:54 UTC, eisenils requested changes
Du hast noch zwei Mal die Add Card Komponente. Bitte erklären oder was löschen. Danke 😅

2021-05-11 08:54 UTC, eisenils commented on src/components/ToDo/AddCard.js
> +              <InputLabel htmlFor="selectGroup">Zuständige*r</InputLabel>
```suggestion
              <InputLabel htmlFor="selectGroup">Zuständig</InputLabel>
```
Sollen wir das noch so ändern. Finde ich einfacher?

2021-05-11 08:54 UTC, eisenils commented on src/components/List/AddCard.js
> +    backgroundColor: "white",
??? 🤔

2021-05-11 08:54 UTC, eisenils commented on src/components/List/AddCard.js
> +              style={{ marginBottom: 10 }}
Sollen wir das nicht besser mit `theme.spacing` lösen?

2021-05-11 11:49 UTC, eisenils reviewed
Ein paar kleine Änderungen noch. Können die gerne nochmal absprechen

2021-05-11 11:49 UTC, eisenils commented on src/components/List/AddCard.js
> +    backgroundColor: "white",
Also hier nochmal schauen, dass es nicht weiß ist :)

2021-05-11 11:49 UTC, eisenils commented on src/components/List/AddCard.js
> +      }); // Liste abstrahieren
```suggestion
      });
```

2021-05-11 11:49 UTC, eisenils commented on src/components/List/AddCard.js
> +  const [title, setTitel] = useState("");
```suggestion
  const [title, setTitle] = useState("");
```
Don't mix Deutsch und Englisch 😉

2021-05-11 11:49 UTC, eisenils commented on src/components/List/AddCard.js
> +    setTitel(e.target.value);
Same here 😃 
```suggestion
  const handleTitle = (e) => {
    setTitle(e.target.value);
```

2021-05-11 11:49 UTC, eisenils commented on src/components/List/AddCard.js
> +      setTitel("");
```suggestion
      setTitle("");
```
You know 🤓

2021-05-11 11:49 UTC, eisenils commented on src/components/List/AddCard.js
> +              onChange={handleTitel}
```suggestion
              onChange={handleTitle}
```
The last one 😅

2021-05-11 11:49 UTC, eisenils commented on src/components/List/List.js
> +    return <Skeleton variant="rect" height={48} animation="wave" />;
```suggestion
    return <Skeleton variant="text" animation="wave" />;
```
Das soll doch die Liste darstellen oder? Dann macht doch der Textbalken mehr Sinn oder?

2021-05-11 11:56 UTC, merged