15: finance popup
WebDesign3-DHBW/GrouBee pull request #34
Opened 2021-05-31 09:21 UTC by NataschaForster

Im Frontend hab ich noch folgendes Problem:

Die Label Texte der Textfelder hängen direkt unter dem Strich und ich weiß aktuell nicht, wie ich das schön beheben kann.

2021-05-31 11:20 UTC, OleMantei commented
remove "status", add "createdDate"

2021-06-01 08:22 UTC, NataschaForster commented
Das Textfeld für den Betrag nimmt noch keine Kommazahlen. Das muss noch angepasst werden.

2021-06-02 06:54 UTC, eisenils requested changes
Kleine changes die ich da requeste

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +  const [title, setTitel] = useState("");
```suggestion
  const [title, setTitle] = useState("");
```

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +    setTitel(e.target.value);
```suggestion
  const handleTitle = (e) => {
    setTitle(e.target.value);
```

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +    setTitel("");
```suggestion
    setTitle("");
```

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +            <TextField id="expense title" label="Ausgabe" onChange={handleTitel} value={title} />
```suggestion
            <TextField id="expense title" label="Ausgabe" onChange={handleTitle} value={title} />
```

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle}>
I like the ID 😆

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +      console.log("infinite loop warning");
Das kommt bei mir gerade jedes Mal wenn ich die Gruppe aufrufe aber nicht infinite sondern pro Aufruf also kann raus oder?
```suggestion
```

2021-06-02 06:54 UTC, eisenils commented on src/components/Finance/FinancePopup.jsx
> +}))(MuiDialogActions);
Hier ebenso wie im Kalender Popup. Geht das evtl noch anders 😇

2021-06-02 07:00 UTC, NataschaForster commented on src/components/Finance/FinancePopup.jsx
> +        <DialogTitle id="filme-serien-hinzufügen" className={classes.dialogTitle}>
ist angepasst

2021-06-02 12:23 UTC, merged